name: Build Geode Mod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Geode CLI
        run: |
          wget https://github.com/geode-sdk/cli/releases/download/v3.8.0/geode-cli-linux.zip -O geode-cli.zip
          unzip geode-cli.zip -d geode-cli
          chmod +x geode-cli/geode
          sudo mv geode-cli/geode /usr/local/bin/geode

      - name: Build mod
        run: geode build

      - name: Upload built mod
        uses: actions/upload-artifact@v4
        with:
          name: sjumpmod
          path: build/*.geode
