name: Build Geode Mod

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake clang unzip wget

      - name: Download Geode CLI v3.7.0
        run: |
          wget https://github.com/geode-sdk/cli/releases/download/v3.7.0/geode-cli-v3.7.0-linux.zip -O geode-cli.zip
          unzip geode-cli.zip
          chmod +x geode
          sudo mv geode /usr/local/bin/

      - name: Build mod
        run: geode build
