name: Build Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download geode-cli
      run: |
        wget https://github.com/geode-sdk/cli/releases/latest/download/geode-cli-linux.zip -O geode-cli.zip
        unzip geode-cli.zip -d geode-cli
        chmod +x geode-cli/geode

    - name: Build mod
      run: |
        ./geode-cli/geode build -- --no-cross

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mod-build
        path: build/
