name: Build Geode Mod

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Geode CLI
        run: |
          wget https://github.com/geode-sdk/cli/releases/latest/download/geode-cli-linux.zip -O geode-cli.zip
          unzip geode-cli.zip -d geode-cli
          sudo mv geode-cli/geode /usr/local/bin/
          chmod +x /usr/local/bin/geode

      - name: Build mod
        run: geode build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sjumpmod
          path: build/*.geode
