name: Build Geode Mod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang make cmake unzip wget

      - name: Download Geode CLI
        run: |
          wget https://github.com/geode-sdk/cli/releases/latest/download/geode-cli-linux.zip -O geode-cli.zip
          unzip geode-cli.zip -d geode-cli
          chmod +x geode-cli/geode
          sudo mv geode-cli/geode /usr/local/bin/geode

      - name: Build mod
        run: geode build

      - name: Upload .geode artifact
        uses: actions/upload-artifact@v3
        with:
          name: mod-geode-file
          path: build/*.geode
