name: Build Geode Mod

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential unzip

    - name: Download Geode CLI
      run: |
        wget https://github.com/geode-sdk/cli/releases/download/v3.6.2/geode-cli-v3.6.2-linux.zip -O geode-cli.zip
        unzip geode-cli.zip -d geode-cli
        chmod +x geode-cli/geode

    - name: Build mod
      run: |
        ./geode-cli/geode build --no-cross

    - name: Upload mod artifact
      uses: actions/upload-artifact@v4
      with:
        name: mod
        path: build/*.geode
